# Utiliser l'image officielle Python 3.12
FROM python:3.12

# Définir le répertoire de travail dans le conteneur
WORKDIR /code

# Installer les dépendances si vous avez un fichier requirements.txt
# (assurez-vous d'ajouter les bibliothèques nécessaires pour les tests comme pytest)
#RUN pip install --no-cache-dir -r requirements.txt

# Ou installer pytest directement si vous n'avez pas de requirements.txt
 RUN pip install --no-cache-dir pytest
